"""add listings table

Revision ID: fb66199f2422
Revises: 002
Create Date: 2026-07-15 13:22:02.991368

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fb66199f2422'
down_revision: Union[str, Sequence[str], None] = '002'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('listings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_name', sa.String(), nullable=False),
    sa.Column('role_title', sa.String(), nullable=False),
    sa.Column('jd_text', sa.Text(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('application_url', sa.String(), nullable=False),
    sa.Column('posted_date', sa.String(), nullable=True),
    sa.Column('listing_type', postgresql.ENUM('internship', 'job', name='listingtype', create_type=False), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_listings_application_url'), 'listings', ['application_url'], unique=True)
    op.create_index(op.f('ix_listings_id'), 'listings', ['id'], unique=False)
    op.add_column('applications', sa.Column('listing_id', sa.Integer(), nullable=False))
    op.drop_index(op.f('ix_applications_job_id'), table_name='applications')
    op.create_index(op.f('ix_applications_listing_id'), 'applications', ['listing_id'], unique=False)
    op.drop_constraint('applications_job_id_fkey', 'applications', type_='foreignkey')
    op.create_foreign_key(None, 'applications', 'listings', ['listing_id'], ['id'], ondelete='CASCADE')
    op.drop_column('applications', 'job_id')
    op.drop_index(op.f('ix_jobs_id'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_url'), table_name='jobs')
    op.drop_table('jobs')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('applications', sa.Column('job_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'applications', type_='foreignkey')
    op.create_foreign_key(op.f('applications_job_id_fkey'), 'applications', 'jobs', ['job_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_applications_listing_id'), table_name='applications')
    op.create_index(op.f('ix_applications_job_id'), 'applications', ['job_id'], unique=False)
    op.drop_column('applications', 'listing_id')
    op.create_table('jobs',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('company', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('location', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('url', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('posted_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('listing_type', postgresql.ENUM('internship', 'job', name='listingtype'), autoincrement=False, nullable=False),
    sa.Column('is_spam', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('spam_confidence', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('jobs_pkey'))
    )
    op.create_index(op.f('ix_jobs_url'), 'jobs', ['url'], unique=True)
    op.create_index(op.f('ix_jobs_id'), 'jobs', ['id'], unique=False)
    op.drop_index(op.f('ix_listings_id'), table_name='listings')
    op.drop_index(op.f('ix_listings_application_url'), table_name='listings')
    op.drop_table('listings')
    # ### end Alembic commands ###
